// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkbkmqohzabswstyurkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYmttcW9oemFic3dzdHl1cmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzE0MDMsImV4cCI6MjA3NDEwNzQwM30._iQI4ClvjTk4hqXQkSSuDm2OFypaO3cGgfNxpX_da1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});